### ISSUE TITLE
Missing DoorCard event

### ISSUE THREAD

**Issue by mawa85** [riogrande75/Dahua#2]
I have the RFID Reader module for the VTO2000A

Looks like the DoorCard event (when Swiping a card) is not implemented yet
 
2020-03-30 15:58:45.000000: Event: AccessControl, Name OpenDoor Method 1, ReaderID 1, UserID 9901
2020-03-30 15:58:45.000000: Unknown event received
array(4) {
  ["id"]=>
  int(2)
  ["method"]=>
  string(24) "client.notifyEventStream"
  ["params"]=>
  array(2) {
    ["SID"]=>
    int(513)
    ["eventList"]=>
    array(1) {
      [0]=>
      array(4) {
        ["Action"]=>
        string(5) "Pulse"
        ["Code"]=>
        string(8) "DoorCard"
        ["Data"]=>
        array(5) {
          ["Check"]=>
          array(2) {
            [0]=>
            int(0)
            [1]=>
            int(0)
          }
          ["LocaleTime"]=>
          string(19) "2020-03-30 17:58:45"
          ["Number"]=>
          string(8) "7a087d0f"
          ["Type"]=>
          int(0)
          ["UTC"]=>
          float(1585587525)
        }
        ["Index"]=>
        int(0)
      }
    }
  }
  ["session"]=>
  int(2147483638)
}

**Comment by riogrande75** [comment]
Added the event.
Pls. test and send me the result ($debug=true)
If you give me an idea, what the $cardno looks like in the VTO's config, I even may implement a card to user table to show cardholder's name in log just like with the fingerprint.

**Comment by mawa85** [comment]
sorry for not responding. Thanks for the fix, will check tomorrow an dprovide you addtional information regarding cardno

**Comment by riogrande75** [comment]
No reply. Guess the fix is working
