### ISSUE TITLE
keepAlive failed

### ISSUE THREAD

**Issue by smarques1976** [riogrande75/Dahua#3]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DahuaVTO2MQTT
 Listens to events from Dahua VTO unit and publishes them via MQTT Message
-----------------------------------------------------------
 Add-on version: 1.0.5
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
parse error: Expected string key before ':' at line 1, column 4
[19:16:27] ERROR: Unknown HTTP error occured
 System:   (armv7 / raspberrypi3)
 Home Assistant Core: 0.107.7
 Home Assistant Supervisor: 214
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:16:35] INFO: Staring Dahua to MQTT
<*** Dahua VTO Event Listener START ***>
Start login
Login success
Started keepAlive thread
keepAlive failed
Failure no keep alive received
Start login
Login success
Started keepAlive thread
keepAlive failed
Failure no keep alive received
Start login
Login success
Started keepAlive thread
keepAlive failed
Failure no keep alive received

I can get the MQTT service and the log keep says that cant keep alive.
What a hack I'm doing wrong??

Thanks

**Comment by smarques1976** [comment]
any feedback can be post?
Thanks

**Comment by riogrande75** [comment]
Where did you get this script <DahuaVTO2MQTT> from? Obviously from another source, because I do not know it.
Did you turn debugging ($debug=1) on?

**Comment by riogrande75** [comment]
No reply for long time. Issue closed.
