### ISSUE TITLE
Documentation for Dahua API?

### ISSUE THREAD

**Issue by cibernox** [riogrande75/Dahua#5]
Hi.

I wanted to know where or how did you find the arguments of the calls made to the dahua doorbell. Things like `'method' => 'RecordFinder.factory.create'` and what arguments each call accepts.

I'm considering expanding the capabilities of my port with some of the ones you have here (and maybe more) to end up creating a fully functional web UI for the doorbell.

**Comment by riogrande75** [comment]
With a call of "service all" in the _Dahua-JSON-Debug-Console_v2.py_ you can see all available method's of the connected Dahua device.
So fare I did not find a clear description, but I guess Dahua's own SDK's could point you into the right direction.
[https://www.dahuasecurity.com/support/downloadCenter/softwares?child=3](url)
The few methods that were implemented by myself were simply traced when playing with the devices using SmarPSS.
