### ISSUE TITLE
help to use this code with VTO1220A and VTO6210

### ISSUE THREAD

**Issue by MohamedHusseinAhmed** [riogrande75/Dahua#6]
Hello,
Could you please help me ? How to use this code to communicate with "VTO1220A and VTO6210"?
I will use them with raspberry pi and flutter (android) application.
for VTO6210 I need to receive a door bill ring, answer it, talk a video call
for VTO1220 I need to receive a call by room number, answer it, talk a video call
Thanks

**Comment by riogrande75** [comment]
Use [DahuaEventHandler.php](https://github.com/riogrande75/Dahua/blob/master/DahuaEventHandler.php), this will show you all kind of events and you can modify it to fit your needs.
Simply adjust user/pwd/ip for your VTO in line #4 and start programm with "php DahuaEventHandler.php".

**Comment by MohamedHusseinAhmed** [comment]
Thanks @riogrande75 , I will try it but actually I didn't use php before so I will look for how to use it.

**Comment by MohamedHusseinAhmed** [comment]
![20210622_224456](https://user-images.githubusercontent.com/16278941/122998224-14668c80-d3ad-11eb-8c8a-aa3ee6046278.jpg)
Hello,
I tried with VTO1220 and login success but keep alive failed. 
Kindly feedback why? And how to fix?
Thanks

**Comment by MohamedHusseinAhmed** [comment]
![20210622_232706](https://user-images.githubusercontent.com/16278941/123001867-82ad4e00-d3b1-11eb-8105-af3ee269ff5d.jpg)
Hello, 
I replaced time() by 50, then added echo for time and packet, then i received the attachment. 

But still i couldn't make a call

**Comment by riogrande75** [comment]
Ok, script works fine, even with your VTO1220.
Making a call is not a function of this script.
Pls. see [DAHUA HTTP API](https://ipcamtalk.com/attachments/amcrest-http-api-9-2020-pdf.76279/) for possible functions and their implementation.
This issue has imho nothing to do with the scripts provided here and will be closed therfor.
